---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: mediawiki
        envFrom:
        - configMapRef:
            name: mariadb-env
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
      initContainers:
      - name: init-mariadb
        image: mariadb:latest
        command: ["sh", "-c", "sleep 10 && mariadb -h localhost -u root -p $MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/init.sql"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
          
      volumes:
      - name: init-scripts
        configMap:
          name: mariadb-init-scripts