---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:1.41.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /var/www/html/LocalSettings.php
          subPath: LocalSettings.php
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
      volumes:
      - name: config
        emptyDir: {}