---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:1.41.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /var/www/html/LocalSettings.php
          subPath: LocalSettings.php
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: mediawiki-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi