---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:1.41.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /var/www/html/LocalSettings.php
          subPath: LocalSettings.php
      volumes:
      - name: config
        emptyDir: {}
      initContainers:
      - name: initialize-mediawiki
        image: mediawiki:1.41.0
        command:
        - /bin/sh
        - -c
        - |
          php /var/www/html/maintenance/install.php \
            --dbname=mediawiki \
            --dbserver="mariadb" \
            --installdbuser=root \
            --installdbpass="$(MYSQL_ROOT_PASSWORD)" \
            --dbuser=mediwiki_user \
            --dbpass=I9WeyZ5aQnEqx3kL5GMQHK \
            --server="http://localhost" \
            --scriptpath=/w \
            --lang=en \
            --pass=Adminpassword \
            "Samit" \
            "Admin"
          cp /var/www/html/LocalSettings.php /config/LocalSettings.php
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password