name: Apply Cluster with Vnet

on:
    workflow_call:
      inputs:
        environment:
          type: string
          description: The environment to apply in
          required: true
  
    workflow_dispatch:
      inputs:
        environment:
          description: The environment to apply in
          required: true

jobs:

  terraform:
    name: apply_cluster
    runs-on: ["self-hosted", "Linux", "X64"]

    environment: ${{ inputs.environment }}

    env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VAR_location: ${{ vars.location }}
        TF_VAR_resource_prefix: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="storage_account_name=tfstatesamitmanna" \
        -backend-config="key=environments/${{ inputs.environment }}/terraform.tfstate"
      working-directory: cluster-with-vnet

    - name: Terraform Apply
      run: |
        terraform apply \
        -auto-approve
      working-directory: cluster-with-vnet