name: Build and Push Mariadb Docker Image

on:
  push:
    paths:
      - 'mariadb/Dockerfile'

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ["self-hosted", "Linux", "X64"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}/mariadb:${{ github.sha }} .
        docker push ${{ env.REGISTRY_NAME }}/mariadb:${{ github.sha }}